apiVersion: skaffold/v2alpha3
kind: Config
deploy:
 kubectl:
   manifests:
    - ./infra/k8s/*

build:
  # local:
  #   push: false 
    googleCloudBuild:
      projectId: ecommerce-service-404508  
    artifacts:
     - image: us.gcr.io/ecommerce-service-404508/auth 
       context: auth 
       docker: 
        dockerfile: Dockerfile
       sync:
         manual:
          - src: 'src/**.ts'
            dest: . 

         
